create database bank;

CREATE  TABLE IF NOT EXISTS bank.`ACCOUNT` (
	`ID_ACCOUNT` INT NOT NULL ,
	`NUMBER` VARCHAR(45) NULL ,
	`BILL` DOUBLE NULL ,
	`DELETED` TINYINT(1) NULL ,
	PRIMARY KEY (`ID_ACCOUNT`) );

CREATE TABLE bank.`CLIENT_ADDITIONAL_INF` (
	`ID_CLIENT_INF` INT(11) NOT NULL,
	`PLACE_OF_BIRTH` VARCHAR(45) DEFAULT NULL,
	`CITY` VARCHAR(45) DEFAULT NULL,
	`ADDRESS` VARCHAR(45) DEFAULT NULL,
	`HOME_PHONE` VARCHAR(45) DEFAULT NULL,
	`MOBILE_PHONE` VARCHAR(45) DEFAULT NULL,
	`EMAIL` VARCHAR(45) DEFAULT NULL,
	`JOB` VARCHAR(45) DEFAULT NULL,
	`POSITION` VARCHAR(45) DEFAULT NULL,
	`FAMILYSTATUS` VARCHAR(45) DEFAULT NULL,
	`NATIONALITY` VARCHAR(45) DEFAULT NULL,
	`DISABILITY` VARCHAR(45) DEFAULT NULL,
	`PENSIONER` TINYINT(1) DEFAULT NULL,
	`INCOME` VARCHAR(45) DEFAULT NULL,
	`RESERVIST` TINYINT(1) DEFAULT NULL,
	PRIMARY KEY (`ID_CLIENT_INF`)
);

CREATE TABLE bank.`PASSPORT` (
	`ID_PASSPORT` INT(11) NOT NULL,
	`SERIES` VARCHAR(45) DEFAULT NULL,
	`PASSNO` VARCHAR(45) DEFAULT NULL,
	`PLACE_OF_ISSUE` VARCHAR(45) DEFAULT NULL,
	`DATE_OF_ISSUE` DATE DEFAULT NULL,
	`IDENTIFICATION_NO` VARCHAR(45) DEFAULT NULL,
	PRIMARY KEY (`ID_PASSPORT`)
);

CREATE TABLE `bank`.`CLIENT_INFORMATION` (
	`ID_CLIENT_INFORMATION` INT NOT NULL,
	`BIRTHDAY` DATE NULL,
	`CLIENT_ADDITIONAL_INF_ID` INT NULL,
	`PASSPORT_ID` INT NULL,
	PRIMARY KEY (`ID_CLIENT_INFORMATION`));

ALTER TABLE `bank`.`client_information`
ADD INDEX `fk_addtitional_inf_idx` (`CLIENT_ADDITIONAL_INF_ID` ASC),
ADD INDEX `fk_passport_idx` (`PASSPORT_ID` ASC);
ALTER TABLE `bank`.`client_information`
ADD CONSTRAINT `fk_addtitional_inf`
FOREIGN KEY (`CLIENT_ADDITIONAL_INF_ID`)
REFERENCES `bank`.`client_additional_inf` (`ID_CLIENT_INF`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_passport`
FOREIGN KEY (`PASSPORT_ID`)
REFERENCES `bank`.`passport` (`ID_PASSPORT`);

CREATE  TABLE IF NOT EXISTS bank.`USER_T` (
	`ID_USER` INT NOT NULL ,
	`LOGIN` VARCHAR(45) NULL ,
	`PASSWORD` VARCHAR(45) NULL ,
	`FIRST_NAME` VARCHAR(45) NULL ,
	`LAST_NAME` VARCHAR(45) NULL ,
	`EMAIL` VARCHAR(45) NULL ,
	`DELETED` TINYINT(1) NULL DEFAULT false ,
	`ROLE` INT NOT NULL ,
	`ACCOUNT_ID` INT NULL ,
	`CLIENT_INFORMATION_ID` INT NULL ,
	PRIMARY KEY (`ID_USER`)
	);

    
ALTER TABLE bank.`USER_T` ADD CONSTRAINT `fk_USER_ACCOUNT1`
	FOREIGN KEY (`ACCOUNT_ID` )
	REFERENCES bank.`ACCOUNT` (`ID_ACCOUNT` );

ALTER TABLE `bank`.`user_t`
ADD INDEX `fk_user_inf_idx` (`CLIENT_INFORMATION_ID` ASC);
ALTER TABLE `bank`.`user_t`
ADD CONSTRAINT `fk_user_inf`
FOREIGN KEY (`CLIENT_INFORMATION_ID`)
REFERENCES `bank`.`client_information` (`ID_CLIENT_INFORMATION`);


	
CREATE  TABLE `bank`.`MESSAGE` (
  `ID_MESSAGE` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `EMAIL` VARCHAR(45) NULL ,
  `MESSAGE` TEXT NULL ,
  `TYPE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID_MESSAGE`) );


